### ISSUE TITLE
Source-only rules will catch all requests without initial referrer

### ISSUE THREAD

**Issue by Infocatcher** [muzuiget/referrer_control#37]
Example:
page http://joyreactor.cc/4915
image http://img0.joyreactor.cc/pics/post/WUMO-Комиксы-мой-перевод-2048247.jpeg

Now paste URL to image into new tab and press enter (looks like all works fine for "View Image" from page context menu).

With <a href="https://addons.mozilla.org/addon/refcontrol/">RefControl</a> it's possible to send fake referrer and get image without watermark (yellow line at bottom).

And unchecked "Ignore blank source request" doesn't help.

**Comment by Infocatcher** [comment]
Oh, interesting. Works fine without rules, but becomes broken with something like
```json
{
    "title": "Referrer Control rule file",
    "date": "2015-04-23 14:13:22",
    "rules": [
        {
            "source": "",
            "target": "/^https?://(?:[^/]+\\.)*addons\\.mozilla\\.org//",
            "value": 0,
            "comment": "RefControl: addons.mozilla.org=@NORMAL"
        },
        {
            "source": "/^https?://(?:[^/]+\\.)*lyrsense\\.com//",
            "target": "",
            "value": 1,
            "comment": "http://lyrsense.com/"
        }
    ]
}
```

**Comment by Infocatcher** [comment]
So, in
```js
    let getFor = function(sourceURI, targetURI, rules, policy) {
        for (let rule of rules) {
            let {source, target, isUrl, url, code} = rule;

            let isMatch;
            if (sourceURI) {
                isMatch = source.test(sourceURI.spec) &&
                                target.test(targetURI.spec);
            } else {
                isMatch = target.test(targetURI.spec);
            }
```
should be something to not check `target.test()` for source-only rules.

**Comment by Gitoffthelawn** [comment]
@Infocatcher I'm trying to understand the title of this issue: "Source-only rules will catch all requests without initial referrer".

Are you saying that every source-only rule gets applied if there is no initial referrer?

**Comment by Infocatcher** [comment]
> Are you saying that every source-only rule gets applied if there is no initial referrer?

Yes,
```js
    let getFor = function(sourceURI /* this is referrer */, targetURI, rules, policy) {
        for (let rule of rules) { // Loop over all rules
            let {source, target, isUrl, url, code} = rule;

            let isMatch;
            if (sourceURI) {
                isMatch = source.test(sourceURI.spec) &&
                                target.test(targetURI.spec);
            } else { // No referrer by default
                // And here used
                // let fakeRegExp = Utils.fakeTrueTest;
                // ...
                // rule.target = target && toRegExp(target) || fakeRegExp;
                isMatch = target.test(targetURI.spec); // Will be always `true`
            }
```

**Comment by Gitoffthelawn** [comment]
@Infocatcher Ugh... I have a bunch of source-only rules.  I'll have to take another look at what referrer is actually being sent.

Can you write a patch to fix it?

**Comment by Infocatcher** [comment]
> Can you write a patch to fix it?

Done: #40
Should be fixed now... it's useless to check target for source-only rules.

And to restore old behavior may be used `^` as target (will match any URL).

**Comment by Gitoffthelawn** [comment]
@Infocatcher Thanks!
@muzuiget What do you think?

**Comment by Gitoffthelawn** [comment]
@muzuiget Any progress in approving this patch?

**Comment by muzuiget** [comment]
Sorry, I still don't understand. Can use "blank source request" feature to do this?

https://github.com/muzuiget/referrer_control/blob/master/docs/en-US/Usage.md#blank-source

**Comment by Infocatcher** [comment]
This is mostly about usage of source-only rules.
E.g. for requests from example.com to any site.
For now these rules will be also applied to all requests without initial/original HTTP referrer.
